### PR TITLE
Colorize help output

### PR DESCRIPTION
**Pull request by zph**
(Builds on #36, will rebase when those land)

Adds colorized output for easier reading :D.

https://www.dropbox.com/s/xpk7s53natouyyo/Screenshot%202019-09-21%2022.51.44.png?dl=0

### CODE REVIEW

**Comment by tj** [comment]
I'm cool with purple target names, I'd maybe leave the descriptions as default (I'm weird I use a white theme haha)

**Comment by zph** [comment]
👍

**Comment by zph** [comment]
Recreated and pushed branch with just the relevant 2 commits :). I left the descriptions as white in this version.

@tj ready for review at your leisure. Thank you!

**Comment by zph** [comment]
New version appearance : 
image

**Comment by zph** [comment]
👍 cool! Thanks @tj

**Pull request merged**
