### PR TITLE
Use go modules for dependency tracking and fix broken dependency (go-env)

### PR DESCRIPTION
**Pull request by zph**
This pr introduces use of `go mod` for handling dependencies. 

It also removes go-env, used in 1 location but broken in newer versions. I replaced it with stdlib code. Fixes warnings/error from mmake.go.

### CODE REVIEW

**Comment by zph** [comment]
(I think CI needs updating/debugging. `make test` and `go build cmd/mmake/mmake.go` are working  locally)

**Comment by zph** [comment]
@tj I don't see a mechanism for me to update CI based on my Github contributor role. But I think it needs a little updating.

If you want to add me there, I can get it working again. I'd also be happy to set it up on Travis or Circle, both of which I'm familiar with.

**Comment by zph** [comment]
I believe the three currently correct steps in Semaphore, as of this PR are:

```
* `go mod download`
* `go build -v ./...`
* `go test -v ./...`
```

This step `go get github.com/campoy/tools/tree` can be dropped thanks to `go mod` handling those duties.

**Comment by tj** [comment]
hmm Semaphore seems messed, not getting any output, we could probably just use GH actions. I'll remove Semaphore for now

**Pull request merged**
